DELETE http://localhost:3001/api/persons/618fea0ee17325ef9b09c6bc

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/618ef9ba8ac069a2e7949753

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Temple Olowonigba",
  "number": "112-917112"
}

###
PUT http://localhost:3001/api/persons/6192583e935143db8220410c
Content-Type: application/json

{
  "name": "Tim Cook",
  "number": "737-373731"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Yi Xiping",
  "number": "419-49916"
}